name: Windows MSVC 6.0 build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: cache toolchain
      id: cache-tc
      uses: actions/cache@v3
      with:
        path: |
          msvc6lt
          vc6varsgh.bat
        key: msvc6lt-cache1

    - name: install toolchain
      if: steps.cache-tc.outputs.cache-hit != 'true'
      run: |
        C:\msys64\usr\bin\wget.exe -q http://mutantstargoat.com/~nuclear/msvc6.zip
        7z x msvc6.zip
        C:\msys64\usr\bin\wget.exe -q http://mutantstargoat.com/~nuclear/vc6fullvarsgh.bat

    - name: build xmon
      shell: cmd
      run: |
        call vc6fullvarsgh.bat
        nmake -f Makefile.vc

    - uses: actions/upload-artifact@v4
      with:
        name: xmon-win32-msvc6
        path: xmon
